### ISSUE TITLE
My submission for `Services Section` challenge

### ISSUE THREAD

**Issue by AhmadNasrHosna** [shadeed/css-garden#1]
Hey Ahmad, this is my submission for `Services Section` Challenge <3..
http://cdpn.io/pen/KKpvNGY

**Comment by shadeed** [comment]
Hello Ahmed!

Wow, this is a really interesting solution. Thank you so much for your submission! Working on adding it to the website.

**Comment by AhmadNasrHosna** [comment]
Thank you so much. ️️

**Comment by shadeed** [comment]
I just added the entry. Thanks a lot!
